# Generated by Django 5.1 on 2024-08-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('idea', 'Edea'), ('work', 'Work'), ('event', 'Event'), ('general', 'General')], max_length=100)),
                ('content', models.TextField()),
                ('date', models.DateField(help_text='Date of the note')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
