# Generated by Django 5.1 on 2024-08-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_note', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
